spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:logistics_db_test}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: info
    com.logistics: debug
    com.logistics.mapper: debug
    com.baomidou.mybatisplus: debug
    org.springframework: info
    org.springframework.web: info
  file:
    name: /var/log/logistics-dashboard/test/application.log
    max-size: 50MB
    max-history: 30
